spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb://192.168.1.241:27017
      database: books
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
